### ISSUE TITLE
[Discussion] Restructure repo for better collaboration

### ISSUE THREAD

**Issue by openhab-5iver** [OH-Jython-Scripters/openhab2-jython#29]
In preparation for OH JSR223-Jython growth, I would like to come up with a way to isolate the core modules/scripts from collaborative contributions, like Esper. I propose we introduce a `community` package with the following directory structure...
```
|_ Community
    |_ Esper
        |_ automation
            |_ jsr223
                |_ community
                    |_ esper
                        |_ components
                           |_ 000_Esper.py
                        |_ esper_example.py
            |_ lib
                |_ python
                    |_ community
                        |_ esper
    |_ Kodi
        |_ automation
            |_ jsr223
                |_ community
                    |_ kodi
                        |_ example_kodi_script.py
            |_ lib
                |_ python
                    |_ community
                        |_ kodi
                    |_ configuration.py.sample
|_ Core
    |_ automation
        |_ jsr223
            |_ community
            |_ core
                |_ components
                |_ 000_startup_delay.py
            |_ personal
        |_ jython
        |_ lib
            |_ python
                |_ community
                |_ core
                |_ personal
                |_ configuration.py.sample
|_ Docs
|_ Script Examples
    |_ Rule Scripts
        |_ automation
            |_ jsr223
                |_ hello_world.py
                |_ timer_example.py
```
One difficulty is that there may be multiple modules with the same name in the `community` package, so I think the Community modules should be kept separate in the repo. For example, two contributors may have modules for Kodi named `community.kodi`. Of course, any Community module could eventually be merged into the `openhab` package, or it could become a separate package of its own.

**Comment by sillyfrog** [comment]
As I'm understanding it more, I very much like the idea of separating out the library components for examples from the "core". I think the core should have just things to make life easier working with openHAB, and all examples (and associated support libraries) moved else where.

I'm also keen for a location for tid-bits of information - at the moment for example I have some notes on getting `pip` working with Jython in openHAB. I could put it in the `README.md`, or add it to the `Docker.md`, but I feel the README is getting a bit large already, and it's not actually Docker specific. I also imagine it'll change over time as other people use it on other platforms.

Thanks!

**Comment by mjcumming** [comment]
Agree with @sillyfrog comments

**Comment by gitMiguel** [comment]
> As I'm understanding it more, I very much like the idea of separating out the library components for examples from the "core". I think the core should have just things to make life easier working with openHAB, and all examples (and associated support libraries) moved else where.

+1 on this. Core should be kept as "clean" as possible


> I'm also keen for a location for tid-bits of information - at the moment for example I have some notes on getting `pip` working with Jython in openHAB. I could put it in the `README.md`, or add it to the `Docker.md`, but I feel the README is getting a bit large already, and it's not actually Docker specific. I also imagine it'll change over time as other people use it on other platforms.

I would propose Wiki. As readme is growing a Wiki would be easier to navigate and find what you need.

**Comment by openhab-5iver** [comment]
As I get some time this weekend, I'll do the restructuring. Consensus seems to be to go with a Wiki, so I'll set that up too.

**Comment by marcelerkel** [comment]
I'm not sure if I like the Person X, Person Y structure. It could complicate things when people are asking for help. "I'm using kodi.py from the repo and it does not work.", "Ok, which version are you using?", "I'm using the latest version, I just did a git pull", "mm.. yeah, I actually meant which persons version are you using?" ...

I'm not against it, but I could see that it would lead to some confusion. I'm already confused about the differences between this repo and Lucid and why I should chose one over the other. Luckily, Lucid is broken for the latest openHAB 2.4 snapshots so I don't have to worry :)

For those who wonder what could end up in this community folder, see (shameless plug): [[Jython] How to: Separating the Business Logic from the rule to make code reuse real easy. Examples included](https://community.openhab.org/t/jython-how-to-separating-the-business-logic-from-the-rule-to-make-code-reuse-real-easy-examples-included/54181)

**Comment by gitMiguel** [comment]
@marcelerkel I think you are right about possible confusion.

> For those who wonder what could end up in this community folder, see (shameless plug): [Jython] How to: Separating the Business Logic from the rule to make code reuse real easy. Examples included

IMHO your kodi scripts fits nicely in community package but for your SmartSwitch script I would suggest that a new "Utils" or "Helpers" section would be created. Under openhab, community or maybe on its own.

**Comment by mjcumming** [comment]
@openhab-5iver 

With the above structure are you proposing we keep User scripts in the current jsr223 folder?

Where would one keep a Class module that they have created. Currently, import looks in the lib directory.

Mike

**Comment by openhab-5iver** [comment]
Big apologies for the major delay! I came down with a terrible cold/flu and needed to take some time to recover. I'm back... for the most part! 

I tried out the Wiki, but it didn't seem like it would work well for documentation, since there is no versioning, branching, or review process. I'll leave the Wiki up for quick notes and thoughts, but as entries evolve, they should be migrated into the docs though. I created a Documents folder, pulled in all the documents, and broke the mega README.md into smaller chunks. This also lets people have a local copy of the docs, rather than being in a Wiki. 

I've also created PR #41 with the proposed directory structure. I've included some notes, but I'll also wrap up the final details into some Contributing Guidelines.

> With the above structure are you proposing we keep User scripts in the current jsr223 folder?
> Where would one keep a Class module that they have created.

@mjcumming , Great questions... there's a gap there! We could separate user scripts by putting them into a separate directory, like `/automation/jsr223/personal/`, and then community scripts in `/automation/jsr223/community/`. Same for modules. I tossed around a few names in my head (personal, user, private, local, etc.), but personal seems to sit well next to community. WDYT?

The one file that does not seem to fit neatly anywhere, is the 000_startup_delay.py. I've recently started to consider renaming the `openhab` package to `core`, and then a `/automation/jsr223/core/` makes sense to me. A `core` package seems more descriptive to me than `openhab`. It'll be a breaking change, but I've migrated to it, and it only took a few minutes to change the imports in my scripts and modules. I've got my fingers crossed that everyone agrees.

> I'm not sure if I like the Person X, Person Y structure. It could complicate things when people are asking for help.

@marcelerkel , I agree. We may find it difficult to separate conflicting code. Contributing Guidelines will be helpful... maybe all/a majority/at least one other contributor to a community module should review/approve changes? A positive of not having them split into separate user directories is that it will drive collaboration. We'll have to see how it goes without them. It also raises the question of what is the best way for someone to share their personal scripts and modules. I think that if they don't fit into our Community directory structure, then a separate repo, an issue in this repo, or the forum could be used for distribution, and then helpful community members can suck their code into the Community structure.

> I'm already confused about the differences between this repo and Lucid and why I should chose one over the other. Luckily, Lucid is broken for the latest openHAB 2.4 snapshots so I don't have to worry :)

Since the unified decorator is looking solid, it's about time to merge the updates to the lucid repo. But there really is no good reason for two repos, so I think it would be best to combine them. There is _a lot_ of good useful stuff in lucid. But there are also some things, IMO, that are too specific to a particular implementation, like use of Sonos for audio, that would fit better in Community rather than Core. @besynnerlig , it's a little early to ask, but WDYT of this possibility?

**Comment by mjcumming** [comment]
Scott, would[ read the docs](https://readthedocs.org/) work for documentation? I am slightly confused on the verbiage of module, component, script etc? I am fine with the openhab->core change. VS Code can do it for me. Agree, that anything that goes into the repo should have a review process - similar to your comments on the lucid library where some of it is very user specific.  One issue that I found painful is the import/reload and I think this is what everyone will want to happen when working on modules in OH. Is there a way to provide a single function that would do this?

**Comment by mjcumming** [comment]
One additional question, should we move to Jython 2.7.1?

**Comment by sillyfrog** [comment]
I have just posted a page to the Wiki about using PIP: https://github.com/OH-Jython-Scripters/openhab2-jython/wiki/Using-PIP-in-Docker
It at least gets something on the Wiki to see how it'll look. To clarify, you can click on the "revisions" link at the top to see changes, and compare them etc (you can't however have a review process). This entry includes using Jpython v2.7.1.

Consolidating the repos sounds good. To date, I have only used the helpers in this repo, and they have been good - but I would like to tweak them a bit (for example `postUpdate` and `sendCommand` should automatically `str()` inputs so you can pass in the native objects - or somehow correctly type cast the inputs).

The other thing I think is ensuring the directory layout makes it easy to work with the repo linked into openHAB (ie: can you drop the "Core" directory into the conf directory in openHAB). I have not wrapped my head around how a final solution would work in practice, so this maybe a dumb point, but want get it out there. Maybe a "contrib" directory, where each script needs to be it's own module (directory), that can then be imported and used as desired. I agree with the removal of usernames, and having it unified to encourage everyone contributing.

Although I have not used it as a contributor, read the docs sounds like a good plan. However I would be suggesting a `README` in each contributed module, rather than the core docs - but could be persuaded to go the other way (for example, a massive module may require a lot of doco).

**Comment by besynnerlig** [comment]
I'm so happy to see the activity here. 

@openhab-5iver
I agree with you totally. We should concentrate or work into a single repo. Consolidation is the way to go. I suggest we should pick out whatever we find useful in Lucid and incorporate them. I totally agree that there is some stuff that is too special to use. 

There are a few small changes in Lucid that I find important to keep if possible. Its about eliminating print statements used in error situations since many users won't be able to see them. Another important change is to re-raise errors after catching them. Those were the reasons that i created lucid initially. Its only a few small changes but IMHO they are necessary. 

I can't be more specific at the moment because I'm at holiday in South East Asia for several more weeks. All I have is a cell phone to work with.  I think it would be quite easy to make a comparison across repos. Or there might be other ways to do it. 

The possibility to eliminate lucid would save it's a lot of work in the end and I really feel that openha b2-jython is going in the right direction now thanks to you guys.  Please also feel free to make any needed changes if any to lucid. 

Cheers

**Comment by openhab-5iver** [comment]
> Scott, would read the docs work for documentation?

@mjcumming , IMO, we really don't need anything more. Our docs can now be accessed as files in the repo, and also at https://oh-jython-scripters.github.io/openhab2-jython/. Here, the `.md`files are being converted to HTML, but they could also be written in HTML or several other formats. https://help.github.com/categories/github-pages-basics/. The only thing missing right now is some navigation, but this can be added. Is there something more you are trying to solve?

> I am slightly confused on the verbiage of module, component, script etc?

Maybe a definitions section? Some Jython and Python reference links would be helpful too. Is everyone aware that every file in the repo (except for some of the Esper libraries) can be edited through a browser, and submitted as a PR? This is much easier than cloning the repo and playing with git. This makes it very easy for anyone to update a file. Probably something good for the docs :wink: .

> One issue that I found painful is the import/reload and I think this is what everyone will want to happen when working on modules in OH. Is there a way to provide a single function that would do this?

A function could be added to reload all imports. This would be good to be opened as a new issue.

> One additional question, should we move to Jython 2.7.1?

Do you mean in regards to the documentation? I'd be hesitant to do this until ESH [#6392](https://github.com/eclipse/smarthome/issues/6392) is resolved.

> The other thing I think is ensuring the directory layout makes it easy to work with the repo linked into openHAB (ie: can you drop the "Core" directory into the conf directory in openHAB). 

@sillyfrog , the way I see it working for a new install is to download the entire repo, do a backup, then copy/paste the contents of the Core directory into `/etc/openhab2/` (or `/opt/openhab2/conf/`). This will create the directory structure starting from `automation` on down. You can then cherry pick the directories in Community that you want and paste them in too. I think this is the easiest/cleanest approach for now, but I've been thinking about ways to automate the install/uninstall. A Core [DirectoryEventTrigger](https://github.com/OH-Jython-Scripters/openhab2-jython/blob/openhab-5iver-restructuring/Core/automation/lib/python/core/triggers.py#L156) rule might work for Community code, and python script could perform the Core install.

> However I would be suggesting a README in each contributed module, rather than the core docs - but could be persuaded to go the other way (for example, a massive module may require a lot of doco).

I think we may want both detailed Community documentation as a README.md in its directroy, but also a summary page in the main docs. Without the latter, I can see a massive pile of cool stuff that you have to dig through to find anything. Community PRs should include both a README and a blurb in the summary. At some point, we should look into using [Sphinx](https://github.com/OH-Jython-Scripters/openhab2-jython/issues/42) to generate the docs.

> I agree with you totally. We should concentrate or work into a single repo. Consolidation is the way to go. I suggest we should pick out whatever we find useful in Lucid and incorporate it into openhab2-jython.

@besynnerlig , I'm so glad you feel this way! I think _every bit_ of functionality in lucid can be included here, either in Core, Community, Documentation, or as an example. I'll create a new PR based on #41 , start diffing the repos, and migrating lucid. This will also provide a good number of use cases for testing out how the restructuring should lay out. I could also migrate the ideAlarm and weatherStationUploader repos. 

@ricadelic , as the only other active maintainer, I definitely do not want to leave you out of the discussion. Are you comfortable with this?

Thinking even bigger, now would be a good time to discuss renaming the organization to OH-JSR223-Scripters, renaming this repo to Jython, and adding repos for Javascript, Groovy, etc. This would provide OH JSR223 users a single source for information and code, with consistency in documentation, process, etc.

**Comment by smar000** [comment]
Thanks @openhab-5iver  for all the tremendous work you are doing in bringing jython to the mainstream! 

One possibly naive question - why do we repeatedly need the `automation` subfolder under each Community and core package? e.g. why not go directly `Community -> Esper -> jsr223`?

**Comment by openhab-5iver** [comment]
> Thanks @openhab-5iver for all the tremendous work you are doing in bringing jython to the mainstream!

:+1:

> but is this likely to confuse new users into thinking they are importing one or other of the smarthome.eclipse.core modules as opposed to just the core jython helpers?

That's a good point. When I was making the changes, I started to get confused a bit myself, but I was hoping it was because I was so used to seeing openhab. At the same time, I was liking the consistency in naming with the ESH core. I'm not sold on the name though... so if we want something different, there'll need to be suggestions. :smile:

> Also one possibly naive question - why do we repeatedly need the automation subfolder under each Community and core package? e.g. why not go directly Community -> Esper -> jsr223?

My reasoning was to make it easier to download and copy/paste a directory structure. It also reinforces for newcomers where things should go. Without automation, you could have a jsr223 and lib folder to copy, instead of just automation.

**Comment by besynnerlig** [comment]
@openhab-5iver
"Very thank you" (as I heard a local say here...). I appreciate what you are doing for migrating lucid (and all other efforts that you do here). Of course I will be grateful if you have the time to migrate the ideAlarm and weatherStationUploader repos. I'm so excited about it and I'm looking forward to check things out further when I eventually return back to Europe again. Anyway, I trust you 100% so as I said before, just do whatever you think is good for bringing the repo forward. ;)

**Comment by smar000** [comment]
> At the same time, I was liking the consistency in naming with the ESH core. I'm not sold on the name though... so if we want something different, there'll need to be suggestions.

Yes, the use of  `core` does give a degree of consistency. If we were to change, maybe something like `jycore`? I'm also not fixated on this, just a thought that crossed my mind whilst going through your samples.

> My reasoning was to make it easier to download and copy/paste a directory structure. It also reinforces for newcomers where things should go. Without automation, you could have a jsr223 and lib folder to copy, instead of just automation.

Ease of copying whole folder makes sense, but wouldn't the same be achieved by copying the whole folder at the module name level, e.g. `esper` folder or `kodi` folder? Again, not fixated on this, but just wondering as to the reasoning.

**Comment by openhab-5iver** [comment]
OK... the PR is merged... let's get some community stuff in there! I have a few things that I'd like to put in, but I think most will end up going under Script Examples, like doing the Design Patterns in Jython. The first thing I will work on though is updating lucid and the other repos to use the API changes, while merging into this one!
