### ISSUE TITLE
"Descendent of"

### ISSUE THREAD

**Issue by mjcumming** [OH-Jython-Scripters/openhab2-jython#37]
In triggers.py, line 174 there is a when "Descendent of" which is not part of the rules DSL. I believe the "Member of" should be changed to match the behavior of "Descendent of" so that it operates on all items (items and groups) and not just items. Correct me if I am wrong.

**Comment by openhab-5iver** [comment]
`Descendent of` adds triggers for each Item that is found as a descendent of the parent group. Groups are not included, as getAllMembers() will recursively search each child group for the member Items. `Member of` only adds triggers for each child of the parent group, including child groups.

These are behaving properly for me... https://community.openhab.org/t/jsr223-jython-simplified-rule-definition-similar-to-rules-dsl-and-universal-decorator/53252/50?u=5iver.

**Comment by mjcumming** [comment]
agree, my mistake.
