### ISSUE TITLE
Missing handler error when using custom TriggerHandlers

### ISSUE THREAD

**Issue by diijkstra** [OH-Jython-Scripters/openhab2-jython#44]
It seems that, custom Jython trigger handlers are not working with recent builds (tested with 2.4.0-M5/M6). At least OSGI and Directory triggers, do register when starting scripts are run, but rules created with said triggers fail with Missing handler error:
```
[INFO ] [smarthome.event.RuleStatusInfoEvent  ] - 590217ff-e78e-427f-9cf4-9874d8340c79 updated: UNINITIALIZED (HANDLER_INITIALIZING_ERROR): Missing handler 'jsr223.OsgiEventTrigger' for module 
```
It took me a day to discover that it is not my rule but simply something is broken ;-) I think I've seen conversation somewhere on openhab forums stating, that this thingy is broken but I've do not see an issue for that.

**Comment by diijkstra** [comment]
Maybe you will have more luck, I've also tried and wasted couple of evenings with miserable failure as a result. My last guess was, around all context stuff being different when rule is executed and when we register handlers (in similar way issues in with jython 2.7.1 are caused by using separate interpreters).

**Comment by openhab-5iver** [comment]
@diijkstra , I figured it out! Details in the OH issue just referenced.
