### ISSUE TITLE
Old reference to LoggerFactory in hello_world.py

### ISSUE THREAD

**Issue by FredericMa** [OH-Jython-Scripters/openhab2-jython#49]
Hi,

I started using Jython today and noticed that the hello_world.py script gives an error: 
`NameError: name 'LoggerFactory' is not defined in <script> at line number 5`
https://github.com/OH-Jython-Scripters/openhab2-jython/blob/ffde155b9259db586a191063f187538620a6b43b/Script%20Examples/hello_world.py#L5
Changing `LoggerFactory` to `logging` fixes the issue.

**Comment by openhab-5iver** [comment]
Thank you! I missed that reference when wrapping up #41. This is now fixed. You're the first person I know of to use the new directory structure. Does it all make sense, or does it seem overly complicated?

**Comment by FredericMa** [comment]
It looks quite clear to me. So the goal is that you copy files from the top folders "Community" and "Script Examples" to the cores "Community" and "Script Examples" folder as you need them?
The only thing that is not very clear to me is; when do you need to put a python file in the jsr223 folder and when in the lib/python folder?

**Comment by openhab-5iver** [comment]
> So the goal is that you copy files from the top folders "Community" and "Script Examples" to the cores "Community" and "Script Examples" folder as you need them?

Close... but not quite... there are community and personal directories at the same level as core. You'd copy into those (not core). Core will stay stripped of any functionality that would be specific to an implementation.

> The only thing that is not very clear to me is; when do you need to put a python file in the jsr223 folder and when in the lib/python folder?

The /jsr223 directory is for scripts, and /lib/python is for packages and modules. Basically, if it;s a rule, put it in jsr223. If it is a file that holds functions or classes for use in scripts, put it in /lib/python.

> Edit: Also the Esper examples are not very clear to me. What is the main goal of using Esper in rules for OpenHAB?

We inherited Esper with the repo, and I haven't really looked at it very deeply... https://www.espertech.com/esper/.

**Comment by FredericMa** [comment]
> Close... but not quite... there are community and personal directories at the same level as core. You'd copy into those (not core). Core will stay stripped of any functionality that would be specific to an implementation.

Correct, bad description from my side.
Thanks for the info!
