### ISSUE TITLE
[Feature Request] Update/migrate ideAlarm

### ISSUE THREAD

**Issue by openhab-5iver** [OH-Jython-Scripters/openhab2-jython#52]

**Comment by fastlorenzo** [comment]
Let me know if some help is needed there

**Comment by openhab-5iver** [comment]
This one should be easy... lucid has two gotchas that I am thinking on. Help with testing would be great!

**Comment by fastlorenzo** [comment]
Great, I already started working on this one as most of the lucid functions it was using are now in core.
I just installed lucid because it was a dependency. I moved the specific lucid functions in a 'utils' module in idealarm.

**Comment by fastlorenzo** [comment]
Ok, I managed to migrate this one and remove the dependency from lucid. 
It's a quick workaround so I have my alarm working until it's fully integrated in this repo.

I can share my changes if needed.

**Comment by openhab-5iver** [comment]
> I can share my changes if needed.

Sure... go ahead and submit a PR... or if that's too much, just post it here!

**Comment by duiffie** [comment]
I'd love to implement ideAlarm in my openHAB 2.4 installation. Do you guys have any idea when the code will be ready to do so?

**Comment by fastlorenzo** [comment]
I’ll check this weekend if I have time to clean the code (remove all my customisation) and make a PR

Lorenzo Bernardi

**Comment by openhab-5iver** [comment]
If you're not familiar with using Git, I can cut a branch and get the directory structure setup for you, so you can just use the GH web interface to paste in the file.

**Comment by fastlorenzo** [comment]
Well, only certain lucid functions from utils are necessary: 
- kw(dict, search)
- isActive(item)
- getItemValue(itemName, defVal)
- sendCommand(itemName, newValue)
- postUpdate(itemName, newValue)
- postUpdateCheckFirst(itemName, newValue, sendACommand=False, floatPrecision=-1)
- sendCommandCheckFirst(itemName, newValue, floatPrecision=-1)
- hasReloadFinished(exitScript=False)

For the moment I moved them in ideAlarm (under a new utils.py file) and made them use core instead of lucid.

**Comment by openhab-5iver** [comment]
I've cut the branch and migrated the files off of lucid, except for the utils, autoremote, sms, tts, and the Wiki. This will all go quickly once I have lucid pushed, as long as migrating the Wiki works like I think it will. :smile:

**Comment by fastlorenzo** [comment]
> 
> 
> > Great, I made a PR which should have it working now 👍
> > In my version I added support for a PIN code entry, so I tried to adapt the base version with what I had to fix to make the version without PIN code working but didn't test it yet.
> > If someone wants to test, you can check the PR I made in that branch
> 
> while starting openHAB I get:
> 
> `2019-01-21 13:26:26.831 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/community/idealarm.py': ImportError: No module named idealarm in <script> at line number 2`

Did you copy the idealarm lib in the correct folder? Did you restart OpenHab after that?

**Comment by duiffie** [comment]
> > > Great, I made a PR which should have it working now 👍
> > > In my version I added support for a PIN code entry, so I tried to adapt the base version with what I had to fix to make the version without PIN code working but didn't test it yet.
> > > If someone wants to test, you can check the PR I made in that branch
> > 
> > 
> > while starting openHAB I get:
> > `2019-01-21 13:26:26.831 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/community/idealarm.py': ImportError: No module named idealarm in <script> at line number 2`
> 
> Did you copy the idealarm lib in the correct folder? Did you restart OpenHab after that?

/etc/openhab2/automation/
├── jsr223
 │   ├── community
 │   ├── core
 │    │   └── components
 │   └── personal
├── jython
└── lib
    └── python
        ├── community
         │   └── idealarm
        ├── core
         │   └── osgi
        └── personal

**Comment by fastlorenzo** [comment]
I don't use the community folder in lib/python.
Looks like it: lib/python/idealarm

Might be the error

**Comment by openhab-5iver** [comment]
Resolved by #91
