### ISSUE TITLE
items.py

### ISSUE THREAD

**Issue by mjcumming** [OH-Jython-Scripters/openhab2-jython#60]
The remove method requires the same string conversion that was added to the add method.

**Comment by openhab-5iver** [comment]
@mjcumming , could you please be more specific? I do not see any string conversion in the items.py.

**Comment by mjcumming** [comment]
sorry, there was an issue in the add method that required to make sure a python string was sent - so I believe @ScottKinSF made a change to add method. Scott?

**Comment by ScottKinSF** [comment]
The latest commit of Core/automation/lib/python/core/items.py has the required change (check for type `basestring` rather than type `string`.

**Comment by openhab-5iver** [comment]
@mjcumming , is this still an issue?

**Comment by ScottKinSF** [comment]
I can't speak for @mjcumming , but it is working for my scripts that dynamically create (and delete) items.

**Comment by openhab-5iver** [comment]
Sounds good too me... we can reopen if Michael still sees an issue.

**Comment by mjcumming** [comment]
agree, its good.
