### ISSUE TITLE
core.items.add_items() throws an exception when tags argument is not supplied

### ISSUE THREAD

**Issue by ScottKinSF** [OH-Jython-Scripters/openhab2-jython#70]
The tags argument to `core.items.add_items()` must be iterable, but the default value specified for the `tags` argument to `add_items()` is `None`, which is not iterable. The default value should be an empty list.

I have submitted PR #69 that fixes this on my system.

**Comment by ScottKinSF** [comment]
I should have caught this when I reviewed PR #63. Sorry 'bout that.

**Comment by openhab-5iver** [comment]
Fixed with #69
