### ISSUE TITLE
At OH start, scripts beneath $OPENHAB_CONF/automation/jsr223/community/ run before those under jsr223/core/

### ISSUE THREAD

**Issue by ScottKinSF** [OH-Jython-Scripters/openhab2-jython#76]
When OH is started, any scripts under $OPENHAB_CONF/automation/jsr223/community/ are loaded and run before any script under $OPENHAB_CONF/automation/jsr223/core/, most notably jsr223/core/000_startup_delay.py.

Logs from my recent OH start:
```
2019-01-23 08:02:14.328 [INFO ][pool-1-thread-1][rt.internal.loader.ScriptFileWatcher] - Loading script 'community/openweathermap/owm_daily_forecast.py'
2019-01-23 08:02:27.480 [INFO ][pool-1-thread-1][rt.internal.loader.ScriptFileWatcher] - Loading script 'core/000_startup_delay.py'
2019-01-23 08:03:37.709 [INFO ][pool-1-thread-1][rt.internal.loader.ScriptFileWatcher] - Loading script 'core/components/100_DirectoryTrigger.py'
```
**Possible fixes (untested):**

- Change the name of community to something like `zzz_community`
- Move `community/` to a new directory immediately below `jsr223`: `jsr223/local/community`.

**Comment by mjcumming** [comment]
@ScottKinSF What about just having a python(jython) script that the jython interpreter loads automatically and have that script load the various directories and modules under user control rather than relying on specific jython versions that seem to behave differently?

**Comment by mjcumming** [comment]
@openhab-5iver I was thinking a .py script that loaded modules/scripts/components in directories not loaded by jython so we do not have to worry about relying on directory and file names to control the order of loading.

**Comment by openhab-5iver** [comment]
> I was thinking a .py script

I could be wrong, but I'm pretty sure scripts have to be under /automation/ for OH to load them.

**Comment by mjcumming** [comment]
Probably not explaining what I was thinking....

If we only had Jython load one script in the automation folder, that script could load other modules in the order desired without worrying about naming conventions and alphabetical order. Ie. I have a script that loads all of the other scripts its needs to run - it doesn't rely on the Jython to load those scripts.

**Comment by ScottKinSF** [comment]
> [the OH doc](https://www.openhab.org/docs/configuration/jsr223.html#script-locations) claims directory names are not considered

In my reading of the OH doc, I don't see such a claim. The doc doesn't seem to say anything about the ordering of the directory traversal during script loading other than it is top down. It would make sense to me that whatever process is performing the traversal and script loading has to have a repeatable method for sequencing through directories that are siblings at any given level of the $OPENHAB_CONF/automation/jsr223/ hierarchy, which to me would reasonably be directory names according to the ASCII collation sequence (case sensitive?).

**Comment by ScottKinSF** [comment]
Loading of JSR223 scripts happens in `smarthome/bundles/automation/org.eclipse.smarthome.automation.module.script.rulesupport/src/main/java/org/eclipse/smarthome/automation/module/script/rulesupport/internal/loader/ScriptFileWatcher.java`. The script files queued for loading are sorted using a case insensitive sort on their path, which accounts for the ordering by directory.

**Comment by openhab-5iver** [comment]
The text at the bottom made it less ambiguous for me...

> the load order will be: 00script.py, 01/script1.py, script2.py, 01/scriptx.py

I'll start looking into this... I just wrapped up adding Jython and Groovy script actions in Paper UI, but waiting for ESH migration before submitting!

**Comment by ScottKinSF** [comment]
Based on my inspection of the relevant Java source code, that text in the documentation is in error. If the files under automation/jsr223/ are as shown in the example:
```
automation/jsr223/
  01/
    script1.py
    scriptx.py
  00script.py
  script2.py
```
the load order will be `00script.py, 01/script1.py, 01/scriptx.py, script2.py`. Easy enough to test that my reading of the Java source is correct.

**Comment by openhab-5iver** [comment]
I agree. The OH doc was originally submitted with that wording on 7/14/17, but there was a change on 7/24/17 that [added the inclusion of the directory name](https://github.com/eclipse/smarthome/pull/3855), but the OH doc was never updated. It puzzles me how the old code would have prevented the loading of the scripts with the same name.

The quick ugly fix is to prefix the directories with a number. The better fix, IMO, is to have ScriptFileWatcher.checkFiles() sort the scripts by filename.

**Comment by ScottKinSF** [comment]
I like your preferred fix, sorting on file names. That is much easier to explain such that any user can understand the script loading order.

**Comment by openhab-5iver** [comment]
I'm updating the docs, and put together some test scripts. These files and directory structure...
```
.
├── 00
│   ├── 00
│   │   ├── 00_00_00.py
│   │   └── 01_00_00.py
│   ├── 00_00.py
│   ├── 01
│   │   ├── 00_00_01.py
│   │   └── 01_00_01.py
│   └── 01_00.py
├── 00.py
├── 01
│   ├── 00
│   │   ├── 00_01_00.py
│   │   └── 01_01_00.py
│   ├── 00_01.py
│   ├── 01
│   │   ├── 00_01_01.py
│   │   └── 01_01_01.py
│   └── 01_01.py
└── 01.py
```
... load in this order...
```
ScriptFileWatcher] - Script loaded: 00.py
ScriptFileWatcher] - Script loaded: 00/00/00_00_00.py
ScriptFileWatcher] - Script loaded: 00/00/01_00_00.py
ScriptFileWatcher] - Script loaded: 00/00_00.py
ScriptFileWatcher] - Script loaded: 00/01/00_00_01.py
ScriptFileWatcher] - Script loaded: 00/01/01_00_01.py
ScriptFileWatcher] - Script loaded: 00/01_00.py
ScriptFileWatcher] - Script loaded: 01.py
ScriptFileWatcher] - Script loaded: 01/00/00_01_00.py
ScriptFileWatcher] - Script loaded: 01/00/01_01_00.py
ScriptFileWatcher] - Script loaded: 01/00_01.py
ScriptFileWatcher] - Script loaded: 01/01/00_01_01.py
ScriptFileWatcher] - Script loaded: 01/01/01_01_01.py
ScriptFileWatcher] - Script loaded: 01/01_01.py
```

I have a couple OH PRs to wrap up, and will then put in a change to ScriptFileWatcher so that just the names of the files are considered. They would then load in this order...
```
ScriptFileWatcher] - Script loaded: 00.py
ScriptFileWatcher] - Script loaded: 00/00_00.py
ScriptFileWatcher] - Script loaded: 00/00/00_00_00.py
ScriptFileWatcher] - Script loaded: 00/01/00_00_01.py
ScriptFileWatcher] - Script loaded: 01/00_01.py
ScriptFileWatcher] - Script loaded: 01/00/00_01_00.py
ScriptFileWatcher] - Script loaded: 01/01/00_01_01.py
ScriptFileWatcher] - Script loaded: 01.py
ScriptFileWatcher] - Script loaded: 00/01_00.py
ScriptFileWatcher] - Script loaded: 00/00/01_00_00.py
ScriptFileWatcher] - Script loaded: 00/01/01_00_01.py
ScriptFileWatcher] - Script loaded: 01/01_01.py
ScriptFileWatcher] - Script loaded: 01/00/01_01_00.py
ScriptFileWatcher] - Script loaded: 01/01/01_01_01.py
```

**Comment by openhab-5iver** [comment]
If anyoe has a minute, I've submitted a PR to change the load order and could use some help communicating the need for the change... https://github.com/openhab/openhab-core/pull/724.

**Comment by openhab-5iver** [comment]
Closed in https://github.com/openhab/openhab-core/pull/724. Wahoo!
