### ISSUE TITLE
OPEN/CLOSED Types doesn't work?

### ISSUE THREAD

**Issue by NicoSoftware** [OH-Jython-Scripters/openhab2-jython#78]
So I'm currently rewriting the Xioami smarthome .rules pattern into Jython:
https://www.openhab.org/addons/bindings/mihome/
Cubes, Motion Sensor etc are working great so far and I will contribute it to the .README if every rules working out.
But I've noticed that the Contact items are not supported or am I wrong?
Code:
```
#Door Sensor #1 Heizungskeller
@rule("Xiaomi Door/Window Sensor Heizungskeller")
@when("Item Door_Openstatus1 received command OPEN")
@when("Item Door_lastopened1 changed")
@when("Item Door_Openstatus1 changed from CLOSED to OPEN")
def heizungskellerLicht(event):
    x = int(items["gMotionOffset"])
    logXC.info("Licht im Heizungskeller: angeschalten, wird in "+str(x)+" Minuten ausgeschalten.")
    sendCommand(items["Yeelights_3"], "ON")
    windowTimer= Timer(x, lambda: events.sendCommand("Yeelights_3","OFF"))
```
Exception:
```
2019-01-31 20:48:47.299 [ERROR] [me.automation.jsr223.jython.triggers] - when: Exception [when: "Item Door_Openstatus1 received command OPEN" could not be parsed because "OPEN" is not a valid command for "Door_Openstatus1"]: [Traceback (most recent call last):

  File "/etc/openhab2/automation/lib/python/core/triggers.py", line 309, in when

    raise ValueError("when: \"{}\" could not be parsed because \"{}\" is not a valid command for \"{}\"".format(target, new_state, trigger_target))

ValueError: when: "Item Door_Openstatus1 received command OPEN" could not be parsed because "OPEN" is not a valid command for "Door_Openstatus1"

]
```
Am I missing something here?
Of course, I could just use the Door_lastopened1 item, but I want to use the full functionalites of the core features!
Thanks alot in advantage

**Comment by openhab-5iver** [comment]
I'm looking into this...

**Comment by openhab-5iver** [comment]
I should have looked at your post better! The only command a contact can receive is REFRESH. This is [the only acceptedCommandType](https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/library/items/ContactItem.java#L45), so there is an error in the Trigger creation. Nothing broken here, except in your rule definition!
