### ISSUE TITLE
Timers and threads being stopped when rule thread exits

### ISSUE THREAD

**Issue by CrazyIvan359** [OH-Jython-Scripters/openhab2-jython#83]
Has anyone used a `threading.Timer` successfully with OH 2.5.0-1512 and Jython 2.7.0?
I am not having any luck getting a thread or timer to outlive the execution of the rule starting it.

Here is the most basic test I have tried that does not work:
```
from threading import Timer
testtimer = None

@rule("test_timer", "test timer")
@when("Time cron 0 * * * * ?")
def rule_testtimer(event):
    logging.getLogger(LOG_MODULE+".test").error("STARTING TEST TIMER")
    global testtimer
    testtimer = Timer(2000, lambda: logging.getLogger(LOG_PREFIX+".test").error("TEST TIMER FIRED"))
    testtimer.start()
```
Which gives me this in the logs:
```
15:01:00.045 [INFO ] [smarthome.event.RuleStatusInfoEvent  ] - 797795b9-4d7f-4645-ad93-31b982e66eec updated: RUNNING
15:01:00.066 [ERROR] [ome.automation.jsr223.jython.test] - STARTING TEST TIMER
15:01:00.068 [DEBUG] [tomation.core.internal.RuleEngineImpl] - The rule '797795b9-4d7f-4645-ad93-31b982e66eec' is executed.
15:01:00.069 [INFO ] [smarthome.event.RuleStatusInfoEvent  ] - 797795b9-4d7f-4645-ad93-31b982e66eec updated: IDLE
```
and the timer never fires.

I was initially trying to spawn a child thread to do a longer fade on some dimmable lights I have, which would run most of the way through its loop the first time but die when the rule thread exited. I then tried doing the same with a timer, but its code never ran because the delay was longer than it took for the rule thread to exit. My best guess at this point is that an child threads are being GCed when the main thread finishes, but from your examples on timers it would seem this shouldn't happen.

Any suggestions or anyone else having this issue?
I have not tried java timers via direct imports or using the OH Action because I won't be able to call a instanced class method from them

**Comment by mjcumming** [comment]
This is how I do timers...

`        def timeout_callback():
            log.info("time out") 

        timer = Timer(time_out_seconds, timeout_callback)
        timer.start()`

**Comment by openhab-5iver** [comment]
In some rules I use the function, like Mike. This lets you do something and log too. In some rules I do it like this...

```
from core.rules import rule
from core.triggers import when
from threading import Timer
testtimer = None

@rule("Test Timer", "A test timer rule")
@when("Time cron 0/10 * * * * ?")
def rule_testtimer(event):
    rule_testtimer.log.error("STARTING TEST TIMER")
    global testtimer
    testtimer = Timer(5, lambda: rule_testtimer.log.error("TEST TIMER FIRED"))
    testtimer.start()
```

**Comment by CrazyIvan359** [comment]
... well don't I feel smart right now... SECONDS not milliseconds haha.
Threads and Timers working just fine, my recollection that python delays are in seconds not milliseconds, not so much
