### ISSUE TITLE
Revise repository permission levels

### ISSUE THREAD

**Issue by besynnerlig** [OH-Jython-Scripters/openhab2-jython#93]
I for example have full permission to this repo. I believe it's better to revise the permission levels for this repo. Using proper permission levels will help prevent accidental damage to the repo.

I believe my own permissions should be restricted to make pull requests.

**Comment by openhab-5iver** [comment]
I added you as a Collaborator to this repo, but I think your Owner status for the organization might affect the permissions. I am also a Collaborator and Owner, but can create pull requests. See if anything has changed now that you are a Collaborator.

**Comment by besynnerlig** [comment]
> As an Owner, you are an Admin on all repos...

All current owners maybe don't have to be owners. I'd prefer not to be an owner to minimize what damage that might arise in case I make a mistake or if my github credentials gets in the wrong hands.


> I think the only way to reduce your permissions on the repos would be to make you only a Member of the organization.

Can you do that for me please?

 

> I see you've made some commits to the lucid repo. You should revert those, and make changes to my fork... https://github.com/openhab-5iver/openhab2-jython/tree/lucid-migration, which is where the PR is coming from. The lucid repo would be deprecated after the PR is merged. My first commit went to the openhab2-jython/lucid-migration branch, but the second one I made as a PR to master, in preparation for the merge. This makes the openhab2-jython/lucid-migration dated... most recent is in my fork.

Sure. Please just let me know when you are ready and let me know what repo to fork.

Cheers!

**Comment by openhab-5iver** [comment]
> Can you do that for me please?

Certainly! Are you suggesting then to move everyone to a Member role of the organization, except for me? Two Owners would be good for redundancy... although worst case you can just fork the repos and start another org. Although, I could add my wife as an Owner too.

> Please just let me know when you are ready and let me know what repo to fork.

I should have the bulk of it done later today. Fork my fork if you want to make changes, or you could wait for the merge and make changes in master. Either works for me. I could also sync up with the lucid-migration branch, if that is easier.

**Comment by besynnerlig** [comment]
> Are you suggesting then to move everyone to a Member role of the organization, except for me? Two Owners would be good for redundancy... although worst case you can just fork the repos and start another org. Although, I could add my wife as an Owner too.

As an organization owner role seems to make everyone admins of all repos, I believe that would be appropriate. One or two "super admins" sounds like a good idea and I believe that you are an obvious good choise as organisation owner for several reasons. You might want to check this first with the other current owners though.  



> I should have the bulk of it done later today. Fork my fork if you want to make changes, or you could wait for the merge and make changes in master. Either works for me. I could also sync up with the lucid-migration branch, if that is easier.

Thanks. I'll leave it to you to decide what's the best fork/branch. When you are ready, I will make a new web fork and create a new branch that I will push all my local repo commits to. When I feel ready, I will make a singe PR. Does that sound good?

**Comment by openhab-5iver** [comment]
> You might want to check this first with the other current owners though.

I haven't seen any activity from them, so I just did it and will change it back if there are concerns.

> Does that sound good?

I see three options. 1) wait for me to merge to master, and then submit a PR to clean things up, 2) make comments with code snippets in the PR and I will put the changes in, 3) submit PRs into my fork, and I will merge them in before merging the main PR into master (this would be trickiest).

**Comment by besynnerlig** [comment]
> I see three options

I'd go for option 1 then. Please le me know when I can commence ;)

**Comment by openhab-5iver** [comment]
OK... hoping to get things in before the sun comes up!

**Comment by besynnerlig** [comment]
> OK... hoping to get things in before the sun comes up!

Please take the time you need. 

Please now when I'm not an organization owner any longer, can you give me permissions to lucid, weatherStationUploader, ideAlarm and mylib?

I have set up pgp encryption and I'd like to test that pgp signing is working by adding a deprecation notice to lucid. ;)

**Comment by openhab-5iver** [comment]
> can you give me permissions to lucid, weatherStationUploader, ideAlarm and mylib?

You are now a Collaborator for these repos.

> Please take the time you need.

I think it's about time for a nap... :zzz:

**Comment by besynnerlig** [comment]
> You are now a Collaborator for these repos.

Thanks. I believe that after adding me as a collaborator, you'll need to choose the appropriate permission level: Write, Read, or Admin. I still can't write anything to it 

You can take it after the nap ;)

**Comment by openhab-5iver** [comment]
> you'll need to choose the appropriate permission level: Write, Read, or Admin. I still can't write anything to it

I set to Read, since it seemed as though you were concerned about pushing. You should be able to make a change and submit a PR. If I set you to Write, you can also do pushes.

**Comment by besynnerlig** [comment]
> I set to Read, since it seemed as though you were concerned about pushing. You should be able to make a change and submit a PR. If I set you to Write, you can also do pushes.

OK, Those repos are outdated anyway so when it comes to them I'm not so worried about having write permissions since the damage I can do is minimal. Please set it to write. But I do not wish to have any write persmissions for openhab2-jython ;) Thanks!

**Comment by openhab-5iver** [comment]
No prob... I went one better and made you a full admin for everything but openhab2-jython.

**Comment by openhab-5iver** [comment]
I think we are all set here
