### ISSUE TITLE
[utils] The full item object is logged instead of the item's name

### ISSUE THREAD

**Issue by besynnerlig** [OH-Jython-Scripters/openhab2-jython#98]
Please see:

https://github.com/besynnerlig/openhab2-jython/commit/ff9a58bf12d9772aee2f05c7049903d434072b20

**Comment by openhab-5iver** [comment]
Could you please submit a PR?

**Comment by besynnerlig** [comment]
Please see https://github.com/OH-Jython-Scripters/openhab2-jython/pull/99
